apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cpr
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /bikes
            pathType: Prefix
            backend:
              service:
                name: my-service
                port: 
                  number: 80
