apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cpr
  #annotations:
    #kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  #defaultBackend:
  #  service:
  #    name: usermgmt-webapp-clusterip-service
  #    port:
  #      number: 80
  rules:
    - http:
        paths:
          - path: /bikes
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
